---
# Group vars for all hosts.

# geerlingguy.apache vars.
apache_remove_default_vhost: true
apache_mods_enabled:
  - "expires.load"
  - "headers.load"
  - "rewrite.load"

# geerlingguy.mysql vars.
mysql_packages:
  - "mariadb-client"
  - "mariadb-server"
  - "python-mysqldb"

# geerlingguy.php vars.
php_default_version_debian: "7.2"
php_install_recommends: "no"
php_date_timezone: "UTC"
php_post_max_size: "64M"
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "On"
php_packages:
  - "libpcre3-dev"
  - "php{{ php_default_version_debian }}-cli"
  - "php{{ php_default_version_debian }}-common"
  - "php{{ php_default_version_debian }}-curl"
  - "php{{ php_default_version_debian }}-dev"
  - "php{{ php_default_version_debian }}-gd"
  - "php{{ php_default_version_debian }}-imap"
  - "php{{ php_default_version_debian }}-json"
  - "php{{ php_default_version_debian }}-mbstring"
  - "php{{ php_default_version_debian }}-mysql"
  - "php{{ php_default_version_debian }}-opcache"
  - "php{{ php_default_version_debian }}-pdo"
  - "php{{ php_default_version_debian }}-xml"
  - "php{{ php_default_version_debian }}-zip"
  - "php-sqlite3"
  - "php-apcu"
  - "php-redis"
  - "libapache2-mod-php{{ php_default_version_debian }}"

# weareinteractive.apt roles.
apt_repositories:
  - repo: "ppa:ondrej/php"
    codename: xenial
    update_cache: true
  - repo: "ppa:ondrej/apache2"
    codename: xenial
    update_cache: true
